; MobileAPI calls: byte offsets into _MobileAPI.Jumptable.
	const_def 0, 2
	const MOBILEAPI_ERRORCHECK
	const MOBILEAPI_INIT
	const MOBILEAPI_WRITECONFIG
	const MOBILEAPI_ISPLOGIN
	const MOBILEAPI_DIAL
	const MOBILEAPI_HANGUP
	const MOBILEAPI_READPHONENUMBERS
	const MOBILEAPI_READUSERID
	const MOBILEAPI_READEMAIL
	const MOBILEAPI_ANSWER
	const MOBILEAPI_SMTPCONNECT
	const MOBILEAPI_SMTPSETADDRESSES
	const MOBILEAPI_SMTPSEND
	const MOBILEAPI_SMTPQUIT
	const MOBILEAPI_POP3QUIT
	const MOBILEAPI_POP3CONNECT
	const MOBILEAPI_POP3STAT
	const MOBILEAPI_POP3LIST
	const MOBILEAPI_POP3RETR
	const MOBILEAPI_POP3DELE
	const MOBILEAPI_POP3HEAD
	const MOBILEAPI_HTTPGET
	const MOBILEAPI_HTTPPOST
	const MOBILEAPI_SENDDATA
	const MOBILEAPI_SETTIMER
	const MOBILEAPI_TELEPHONESTATUS
	const MOBILEAPI_STOP
	const MOBILEAPI_END
	const MOBILEAPI_READCONFIG
	const MOBILEAPI_GETDATA
	const MOBILEAPI_TCPCUT
; A second entry pointing to the same handler as MOBILEAPI_ISPLOGIN.
	const MOBILEAPI_ISPLOGIN_ALIAS
	const MOBILEAPI_INIT_ALT
	const MOBILEAPI_TELEPHONESTATUS_ALT
DEF NUM_MOBILE_API_CALLS EQU const_value / 2

; wMobileSDK_Status bits
	const_def
	const MOBILE_SDK_BUSY_F
	const MOBILE_SDK_ERROR_F
	const MOBILE_SDK_RECV_BUFFER_FULL_F
	const MOBILE_SDK_DATA_READY_F

; MobileEZChatCategoryPointers indexes (see mobile/fixed_words.asm)
	const_def
	const EZCHAT_POKEMON
	const EZCHAT_TYPES
	const EZCHAT_GREETINGS
	const EZCHAT_PEOPLE
	const EZCHAT_BATTLE
	const EZCHAT_EXCLAMATIONS
	const EZCHAT_CONVERSATION
	const EZCHAT_FEELINGS
	const EZCHAT_CONDITIONS
	const EZCHAT_LIFE
	const EZCHAT_HOBBIES
	const EZCHAT_ACTIONS
	const EZCHAT_TIME
	const EZCHAT_FAREWELLS
	const EZCHAT_THISANDTHAT

DEF NUM_KANA EQU 45 ; length of SortedPokemon table (see mobile/fixed_words.asm)

DEF MOBILE_LOGIN_PASSWORD_LENGTH EQU 17
DEF MOBILE_LOGIN_PASSWORD_MAX_LENGTH EQU MOBILE_LOGIN_PASSWORD_LENGTH - 1
DEF MOBILE_PHONE_NUMBER_LENGTH EQU 20
DEF MOBILE_LOGIN_ID_LENGTH EQU 32
DEF MOBILE_URL_MAX_LENGTH EQU 165
DEF MOBILE_RECEIVE_BUFFER_SIZE EQU $1000
DEF MOBILE_DOWNLOAD_FEE_LENGTH EQU 3
DEF MOBILE_DOWNLOAD_FEE_NONDIGIT EQU "/"

; wMobileDownloadFlags: bit 0 selects the second receive buffer; the high
; bits identify the API to resume when the first receive buffer fills.
DEF MOBILE_DOWNLOAD_OVERFLOW_F EQU 0
DEF MOBILE_DOWNLOAD_OVERFLOW EQU 1 << MOBILE_DOWNLOAD_OVERFLOW_F
DEF MOBILE_DOWNLOAD_POP3_RETR EQU 1 << 4
DEF MOBILE_DOWNLOAD_POP3_HEAD EQU 1 << 5
DEF MOBILE_DOWNLOAD_HTTP_POST EQU 1 << 6
DEF MOBILE_DOWNLOAD_HTTP_GET EQU 1 << 7

; Legacy three-minute limit, counted by Mobile_CheckLegacyInactivityTimeout.
DEF MOBILE_INACTIVITY_TIMEOUT_FRAMES EQU 3 * 60 * 60
DEF MOBILE_RESULT_CANCELED EQU $a
DEF MOBILE_ERROR_INVALID_DOWNLOAD EQU $d3
DEF MOBILE_ERROR_INACTIVITY_TIMEOUT EQU $d6
DEF MOBILE_ERROR_STADIUM_INDEX EQU $d8
DEF MOBILE_ERROR_URL_TOO_LONG EQU $da

; Maximum amount of time allowed for mobile battles each day
DEF MOBILE_BATTLE_ALLOWED_SECONDS EQU 0
DEF MOBILE_BATTLE_ALLOWED_MINUTES EQU 10

; Trade corner request size
; DION addr $1e + request $8 + Name $5
; + party struct $30 + OT $5 + NICK $5
; + JP Mail struct $2a
DEF MOBILE_EMAIL_LENGTH EQU $1e
DEF TRADE_CORNER_REQUEST_LENGTH EQU $8f

DEF EASY_CHAT_MESSAGE_WORD_COUNT EQU 6
DEF EASY_CHAT_MESSAGE_LENGTH EQU EASY_CHAT_MESSAGE_WORD_COUNT * 2 ; every word uses 2 bytes

; DisplayMobileError / MobileErrorCodeTable
DEF MOBILE_SDK_ERROR_FIRST EQU $10
DEF MOBILE_SDK_ERROR_LAST EQU $33
DEF NUM_MOBILE_SDK_ERRORS EQU MOBILE_SDK_ERROR_LAST - MOBILE_SDK_ERROR_FIRST + 1
; Game-defined errors are displayed as 101-(code - MOBILE_GAME_ERROR_FIRST + 1).
DEF MOBILE_GAME_ERROR_FIRST EQU $d0
DEF MOBILE_GAME_ERROR_LAST EQU $da
DEF NUM_MOBILE_GAME_ERRORS EQU MOBILE_GAME_ERROR_LAST - MOBILE_GAME_ERROR_FIRST + 1
DEF MOBILE_ERROR_DEFAULT EQU $d9
DEF MOBILE_TEXTBOX_PALETTE EQU 6

; DisplayMobileError.Jumptable / wMobileErrorJumptableIndex
	const_def
	const MOBILE_ERROR_INIT
	const MOBILE_ERROR_WAIT_BUTTON
	const MOBILE_ERROR_INIT_NO_FADE
DEF NUM_MOBILE_ERROR_STATES EQU const_value

; MobileConnectionDialog.Jumptable / wMobileDialogJumptableIndex
	const_def
	const MOBILE_DIALOG_INIT
	const MOBILE_DIALOG_CALL_CENTER
	const MOBILE_DIALOG_CONNECTION_FEES
	const MOBILE_DIALOG_ADAPTER_READY
	const MOBILE_DIALOG_CHECK_ADAPTER_READY
	const MOBILE_DIALOG_CONNECTED
	const MOBILE_DIALOG_START_DELAY
	const MOBILE_DIALOG_WAIT_FOR_COMMUNICATING
	const MOBILE_DIALOG_COMMUNICATING
	const MOBILE_DIALOG_DOWNLOAD_FEE_INTRO
	const MOBILE_DIALOG_DOWNLOAD_FEE
	const MOBILE_DIALOG_CHECK_DOWNLOAD_FEE
	const MOBILE_DIALOG_CONNECTION_CLOSED
	const MOBILE_DIALOG_CONNECTION_TIME
	const MOBILE_DIALOG_CLOSE
	const MOBILE_DIALOG_PLACE_CANCEL_MENU
	const MOBILE_DIALOG_UPDATE_CANCEL_MENU
	const MOBILE_DIALOG_NEW_DATA
	const MOBILE_DIALOG_DOWNLOAD_DATA
	const MOBILE_DIALOG_CHECK_DOWNLOAD_DATA
	const MOBILE_DIALOG_PREVIOUSLY_DOWNLOADED
	const MOBILE_DIALOG_DATA_MISSING
	const MOBILE_DIALOG_REDOWNLOAD_DATA
	const MOBILE_DIALOG_CHECK_REDOWNLOAD_DATA
	const MOBILE_DIALOG_NO_NEW_DATA
	const MOBILE_DIALOG_WAIT_NO_NEW_DATA
	const MOBILE_DIALOG_CANCEL_DOWNLOAD
	const MOBILE_DIALOG_CHECK_CANCEL_DOWNLOAD
	const MOBILE_DIALOG_COMMUNICATING_WITH_CANCEL
	const MOBILE_DIALOG_DOWNLOAD_NEWS
	const MOBILE_DIALOG_CHECK_DOWNLOAD_NEWS
	const MOBILE_DIALOG_NO_NEWS
	const MOBILE_DIALOG_WAIT_NO_NEWS
DEF NUM_MOBILE_DIALOG_STATES EQU const_value

DEF MOBILE_DIALOG_DELAY_FRAMES EQU 128

; Mobile_WriteMessage.Jumptable / wMobileMessageJumptableIndex
	const_def
	const MOBILE_MESSAGE_IDLE
	const MOBILE_MESSAGE_EXPAND_TEXT
	const MOBILE_MESSAGE_PRINT_TEXT
DEF NUM_MOBILE_MESSAGE_STATES EQU const_value

DEF MOBILE_MESSAGE_BUFFER_LENGTH EQU 140

; MobilePhoneAnimations / wMobilePhoneAnimation
	const_def
	const MOBILE_PHONE_ANIM_DIALING
	const MOBILE_PHONE_ANIM_SIGNAL
	const MOBILE_PHONE_ANIM_IDLE
	const MOBILE_PHONE_ANIM_SIGNAL_REVERSE
DEF NUM_MOBILE_PHONE_ANIMS EQU const_value

; MobilePhoneFrames / wMobilePhoneFrame
	const_def
	const MOBILE_PHONE_FRAME_IDLE
	const MOBILE_PHONE_FRAME_SIGNAL_1
	const MOBILE_PHONE_FRAME_SIGNAL_2
	const MOBILE_PHONE_FRAME_SIGNAL_3
	const MOBILE_PHONE_FRAME_DIALING_1
	const MOBILE_PHONE_FRAME_DIALING_2
	const MOBILE_PHONE_FRAME_DIALING_3
	const MOBILE_PHONE_FRAME_DIALING_4
	const MOBILE_PHONE_FRAME_DIALING_5
	const MOBILE_PHONE_FRAME_SIGNAL_4
	const MOBILE_PHONE_FRAME_SIGNAL_5
	const MOBILE_PHONE_FRAME_SIGNAL_REVERSE_1
	const MOBILE_PHONE_FRAME_SIGNAL_REVERSE_2
	const MOBILE_PHONE_FRAME_SIGNAL_REVERSE_3
	const MOBILE_PHONE_FRAME_SIGNAL_REVERSE_4
	const MOBILE_PHONE_FRAME_SIGNAL_REVERSE_5
DEF NUM_MOBILE_PHONE_FRAMES EQU const_value

DEF MOBILE_PHONE_ANIM_END EQU $ff
DEF MOBILE_PHONE_FRAME_DURATION EQU 8
DEF MOBILE_PHONE_OAM_COUNT EQU 8
DEF MOBILE_PHONE_TILE EQU $60

; wMobileDialogContext
	const_def
	const MOBILE_DIALOG_CONTEXT_OVERWORLD
	const MOBILE_DIALOG_CONTEXT_STADIUM
	const MOBILE_DIALOG_CONTEXT_NEWS

; MobilePasswordStatePointers / wMobilePasswordJumptableIndex
	const_def
	const MOBILE_PASSWORD_INIT_CURSORS
	const MOBILE_PASSWORD_JOYPAD
	const MOBILE_PASSWORD_ASK_SAVE
	const MOBILE_PASSWORD_SAVE_JOYPAD
	const MOBILE_PASSWORD_STORE
	const MOBILE_PASSWORD_WAIT_SAVED
	const MOBILE_PASSWORD_EMPTY
	const MOBILE_PASSWORD_WAIT_EMPTY
DEF NUM_MOBILE_PASSWORD_STATES EQU const_value

DEF MOBILE_PASSWORD_STATE_SIZE EQU 8
DEF MOBILE_PASSWORD_KEYBOARD_COLUMNS EQU 14
DEF MOBILE_PASSWORD_KEYBOARD_ROWS EQU 4
DEF MOBILE_PASSWORD_KEYBOARD_SYMBOLS EQU 1
DEF MOBILE_PASSWORD_MESSAGE_DELAY EQU 30
DEF MOBILE_PASSWORD_COMMAND_COLUMN_SPACING EQU 5
DEF MOBILE_ASCII_FONT_OFFSET EQU $20
DEF MOBILE_PASSWORD_POSITION_CURSOR_MASK EQU 1 << 0
DEF MOBILE_PASSWORD_KEYBOARD_CURSOR_MASK EQU 1 << 1

	const_def
	const MOBILE_PASSWORD_COMMAND_SWITCH
	const MOBILE_PASSWORD_COMMAND_CANCEL
	const MOBILE_PASSWORD_COMMAND_DONE

; MobileCenterStatePointers / wMobileCenterJumptableIndex
	const_def
	const MOBILE_CENTER_CONNECTING_MESSAGE
	const MOBILE_CENTER_INIT_ADAPTER
	const MOBILE_CENTER_WAIT_INIT
	const MOBILE_CENTER_READ_NUMBERS
	const MOBILE_CENTER_WAIT_NUMBERS
	const MOBILE_CENTER_DRAW_LIST
	const MOBILE_CENTER_INIT_CURSORS
	const MOBILE_CENTER_JOYPAD
	const MOBILE_CENTER_CONFIRM_JOYPAD
	const MOBILE_CENTER_WAIT_SAVED
	const MOBILE_CENTER_ERROR_DELAY
	const MOBILE_CENTER_SHOW_ERROR
DEF NUM_MOBILE_CENTER_STATES EQU const_value

DEF NUM_MOBILE_CENTERS EQU 3
DEF MOBILE_CENTER_NUMBER_LENGTH EQU 16
DEF MOBILE_CENTER_NAME_LENGTH EQU 16
DEF MOBILE_CENTER_TABLE_SIZE EQU NUM_MOBILE_CENTERS * (MOBILE_CENTER_NUMBER_LENGTH + 1 + MOBILE_CENTER_NAME_LENGTH + 1)
DEF MOBILE_CENTER_ROW_SPACING EQU 3
DEF MOBILE_CENTER_SAVED_DELAY EQU 30
DEF MOBILE_CENTER_ERROR_DELAY_FRAMES EQU 40
DEF MOBILE_CENTER_LIST_CURSOR_MASK EQU 1 << 2
DEF MOBILE_CENTER_CONFIRM_CURSOR_MASK EQU 1 << 3

; MobileStadiumStatePointers / wJumptableIndex
	const_def
	const MOBILE_STADIUM_LOAD_PALETTES
	const MOBILE_STADIUM_WAIT_OPEN_MESSAGE
	const MOBILE_STADIUM_ENTRY_MESSAGE
	const MOBILE_STADIUM_CONFIRM_MENU
	const MOBILE_STADIUM_CONFIRM_JOYPAD
	const MOBILE_STADIUM_DOWNLOAD
	const MOBILE_STADIUM_SUCCESS
DEF NUM_MOBILE_STADIUM_STATES EQU const_value

DEF MOBILE_STADIUM_OPEN_DELAY      EQU 16
DEF MOBILE_STADIUM_DATA_SIZE       EQU $1000
DEF MOBILE_STADIUM_ID_OFFSET       EQU $fea
DEF MOBILE_STADIUM_ID_LENGTH       EQU 16
DEF MOBILE_STADIUM_CHECKSUM_LENGTH EQU MOBILE_STADIUM_DATA_SIZE - 4
DEF MOBILE_STADIUM_DOWNLOAD_LENGTH EQU MOBILE_RECEIVE_BUFFER_SIZE - 2

; Mobile_DownloadStadiumJumptable / wMobileConnectionJumptableIndex
	const_def
	const MOBILE_STADIUM_DOWNLOAD_INIT_DIALOG
	const MOBILE_STADIUM_DOWNLOAD_INIT_ADAPTER
	const MOBILE_STADIUM_DOWNLOAD_WAIT_INIT
	const MOBILE_STADIUM_DOWNLOAD_READ_PHONE
	const MOBILE_STADIUM_DOWNLOAD_WAIT_PHONE
	const MOBILE_STADIUM_DOWNLOAD_READ_LOGIN
	const MOBILE_STADIUM_DOWNLOAD_WAIT_LOGIN
	const MOBILE_STADIUM_DOWNLOAD_READ_EMAIL
	const MOBILE_STADIUM_DOWNLOAD_WAIT_EMAIL
	const MOBILE_STADIUM_DOWNLOAD_LOGIN_ISP
	const MOBILE_STADIUM_DOWNLOAD_WAIT_LOGIN_ISP
	const MOBILE_STADIUM_DOWNLOAD_STOP_PICHU
	const MOBILE_STADIUM_DOWNLOAD_GET_INDEX
	const MOBILE_STADIUM_DOWNLOAD_WAIT_INDEX
	const MOBILE_STADIUM_DOWNLOAD_PARSE_INDEX
	const MOBILE_STADIUM_DOWNLOAD_NEW_DATA
	const MOBILE_STADIUM_DOWNLOAD_PREVIOUS_DATA
	const MOBILE_STADIUM_DOWNLOAD_CONFIRM_DATA
	const MOBILE_STADIUM_DOWNLOAD_GET_DATA
	const MOBILE_STADIUM_DOWNLOAD_WAIT_DATA
	const MOBILE_STADIUM_DOWNLOAD_LOGOUT
	const MOBILE_STADIUM_DOWNLOAD_WAIT_LOGOUT
	const MOBILE_STADIUM_DOWNLOAD_DISCONNECT_DIALOG
	const MOBILE_STADIUM_DOWNLOAD_END
	const MOBILE_STADIUM_DOWNLOAD_WAIT_END
	const MOBILE_STADIUM_DOWNLOAD_DONE
	const MOBILE_STADIUM_DOWNLOAD_NO_NEW_DATA
	const MOBILE_STADIUM_DOWNLOAD_WAIT_NO_NEW_DATA
	const MOBILE_STADIUM_DOWNLOAD_CANCEL
	const MOBILE_STADIUM_DOWNLOAD_WAIT_CANCEL
	const MOBILE_STADIUM_DOWNLOAD_ERROR
	const MOBILE_STADIUM_DOWNLOAD_WAIT_ERROR
	const MOBILE_STADIUM_DOWNLOAD_UNUSED_DISCONNECT
DEF NUM_MOBILE_STADIUM_DOWNLOAD_STATES EQU const_value

DEF MOBILE_STADIUM_TIME_FIELDS           EQU 3
DEF MOBILE_STADIUM_TIME_WILDCARD         EQU $ff
DEF MOBILE_STADIUM_CHECKSUM_FIELD_LENGTH EQU 4
; ASCII "P3", followed by the two-byte checksum.
DEF MOBILE_STADIUM_CHECKSUM_SIGNATURE    EQU $3350

; MobilePichu_RunState.Jumptable / wMobilePichuJumptableIndex
	const_def
	const MOBILE_PICHU_LOAD_TILEMAP
	const MOBILE_PICHU_LOAD_BORDER
	const MOBILE_PICHU_LOAD_SPRITES
	const MOBILE_PICHU_ANIMATE
	const MOBILE_PICHU_RESTORE_OVERWORLD
	const MOBILE_PICHU_RESTORE_STADIUM
	const MOBILE_PICHU_RESTORE_NEWS
DEF NUM_MOBILE_PICHU_STATES EQU const_value

DEF MOBILE_PICHU_FRAME_HIDDEN       EQU $fd
DEF MOBILE_PICHU_BALL_INITIAL_DELAY EQU 7
DEF MOBILE_PICHU_BALL_FOLLOW_SHIFT  EQU 5
DEF MOBILE_PICHU_MAX_OBJECTS        EQU 16
DEF MOBILE_PICHU_BALL_OBJECTS       EQU 9
DEF MOBILE_PICHU_BORDER_ROWS        EQU 12
DEF MOBILE_PICHU_WINDOW_Y           EQU 6 * TILE_WIDTH
DEF MOBILE_PICHU_INITIAL_X          EQU SCREEN_WIDTH_PX + 2 * TILE_WIDTH
DEF MOBILE_PICHU_INITIAL_Y          EQU 9 * TILE_WIDTH
DEF MOBILE_PICHU_WRAP_THRESHOLD     EQU $b0
DEF MOBILE_PICHU_MIRROR_X           EQU 10 * TILE_WIDTH
DEF MOBILE_PICHU_MIRROR_Y           EQU 12 * TILE_WIDTH
DEF MOBILE_PICHU_MUSIC_FADE         EQU 8
DEF MOBILE_PICHU_NUM_TILES          EQU 193
; Nine 16-byte blocks per GDMA; chunk starts are four tilemap rows apart.
DEF MOBILE_PICHU_DMA_LENGTH         EQU 8

; MobilePichuMovementPointers / wMobilePichuMovementIndex
	const_def
	const MOBILE_PICHU_MOVE_IDLE
	const MOBILE_PICHU_MOVE_INIT_HORIZONTAL
	const MOBILE_PICHU_MOVE_START_LEFT
	const MOBILE_PICHU_MOVE_LEFT
	const MOBILE_PICHU_MOVE_START_RIGHT
	const MOBILE_PICHU_MOVE_RIGHT
	const MOBILE_PICHU_MOVE_INIT_VERTICAL
	const MOBILE_PICHU_MOVE_START_DOWN
	const MOBILE_PICHU_MOVE_DOWN
	const MOBILE_PICHU_MOVE_START_UP
	const MOBILE_PICHU_MOVE_UP
	const MOBILE_PICHU_MOVE_INIT_APPEAR
	const MOBILE_PICHU_MOVE_APPEAR
	const MOBILE_PICHU_MOVE_WAIT_APPEAR
	const MOBILE_PICHU_MOVE_INIT_FINISH
	const MOBILE_PICHU_MOVE_START_FINISH
	const MOBILE_PICHU_MOVE_APPROACH_FINISH
	const MOBILE_PICHU_MOVE_FINISH
	const MOBILE_PICHU_MOVE_UNUSED_FINISH
DEF NUM_MOBILE_PICHU_MOVEMENTS EQU const_value

; MobilePichuAnimations / wMobilePichuAnimation
	const_def
	const MOBILE_PICHU_ANIM_LEFT
	const MOBILE_PICHU_ANIM_RIGHT
	const MOBILE_PICHU_ANIM_UP
	const MOBILE_PICHU_ANIM_DOWN
	const MOBILE_PICHU_ANIM_APPEAR_UPPER
	const MOBILE_PICHU_ANIM_APPEAR_LOWER
	const MOBILE_PICHU_ANIM_FINISH
	const MOBILE_PICHU_ANIM_BALL
DEF NUM_MOBILE_PICHU_ANIMS EQU const_value

; MobilePichuFrames / wMobilePichuFrame / wMobilePichuBallFrame
	const_def
	const MOBILE_PICHU_FRAME_LEFT_1
	const MOBILE_PICHU_FRAME_LEFT_2
	const MOBILE_PICHU_FRAME_LEFT_3
	const MOBILE_PICHU_FRAME_LEFT_4
	const MOBILE_PICHU_FRAME_RIGHT_1
	const MOBILE_PICHU_FRAME_RIGHT_2
	const MOBILE_PICHU_FRAME_RIGHT_3
	const MOBILE_PICHU_FRAME_RIGHT_4
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_1
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_2
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_3
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_4
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_5
	const MOBILE_PICHU_FRAME_APPEAR_UPPER_6
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_1
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_2
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_3
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_4
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_5
	const MOBILE_PICHU_FRAME_APPEAR_LOWER_6
	const MOBILE_PICHU_FRAME_UP_1
	const MOBILE_PICHU_FRAME_UP_2
	const MOBILE_PICHU_FRAME_UP_3
	const MOBILE_PICHU_FRAME_DOWN_1
	const MOBILE_PICHU_FRAME_DOWN_2
	const MOBILE_PICHU_FRAME_DOWN_3
	const MOBILE_PICHU_FRAME_DOWN_4
	const MOBILE_PICHU_FRAME_DOWN_5
	const MOBILE_PICHU_FRAME_FINISH_1
	const MOBILE_PICHU_FRAME_FINISH_2
	const MOBILE_PICHU_FRAME_FINISH_3
	const MOBILE_PICHU_FRAME_FINISH_4
	const MOBILE_PICHU_FRAME_FINISH_5
	const MOBILE_PICHU_FRAME_FINISH_6
	const MOBILE_PICHU_FRAME_FINISH_7
	const MOBILE_PICHU_FRAME_FINISH_8
	const MOBILE_PICHU_FRAME_BALL_1
	const MOBILE_PICHU_FRAME_BALL_2
	const MOBILE_PICHU_FRAME_BALL_3
	const MOBILE_PICHU_FRAME_BALL_4
	const MOBILE_PICHU_FRAME_BALL_5
	const MOBILE_PICHU_FRAME_BALL_6
	const MOBILE_PICHU_FRAME_BALL_7
	const MOBILE_PICHU_FRAME_BALL_8
	const MOBILE_PICHU_FRAME_BALL_9
	const MOBILE_PICHU_FRAME_BALL_10
	const MOBILE_PICHU_FRAME_BALL_11
DEF NUM_MOBILE_PICHU_FRAMES EQU const_value
	assert NUM_MOBILE_PICHU_FRAMES <= MOBILE_PICHU_FRAME_HIDDEN

DEF MOBILE_PICHU_ANIM_LOOP       EQU $fe
DEF MOBILE_PICHU_ANIM_END        EQU $ff
DEF MOBILE_PICHU_OBJECTS_PER_ROW EQU 4
DEF MOBILE_PICHU_LEFT_EDGE       EQU OAM_X_OFS - 4 * TILE_WIDTH
DEF MOBILE_PICHU_RIGHT_EDGE      EQU SCREEN_WIDTH_PX + OAM_X_OFS
DEF MOBILE_PICHU_TOP_EDGE        EQU MOBILE_PICHU_WINDOW_Y - TILE_WIDTH
DEF MOBILE_PICHU_BOTTOM_EDGE     EQU SCREEN_HEIGHT_PX + OAM_Y_OFS


DEF MOBILE_PHONE_DIGITS_LENGTH EQU 16
DEF MOBILE_PHONE_BCD_LENGTH EQU MOBILE_PHONE_DIGITS_LENGTH / 2
DEF MOBILE_DIALPAD_MIN_DIGITS EQU 7
DEF MOBILE_DIALPAD_STATE_SIZE EQU 10
DEF MOBILE_DIALPAD_KEY_DELAY EQU 5

; MobileDialpadStatePointers / wMobileDialpadJumptableIndex
	const_def
	const MOBILE_DIALPAD_INIT_CURSOR
	const MOBILE_DIALPAD_JOYPAD
	const MOBILE_DIALPAD_WAIT_KEY_HIGHLIGHT
	const MOBILE_DIALPAD_WAIT_ACCEPT
	const MOBILE_DIALPAD_ERROR_JOYPAD
	const MOBILE_DIALPAD_WAIT_CANCEL
DEF NUM_MOBILE_DIALPAD_STATES EQU const_value

; wMobileDialpadFlags
	const_def 4
	const MOBILE_DIALPAD_HOME_PALETTE_F
	const MOBILE_DIALPAD_ACCEPTED_F
	const MOBILE_DIALPAD_ERROR_F
	const MOBILE_DIALPAD_UPDATE_ATTRMAP_F

; MobileDialpadKeys / wMobileDialpadCursor / wMobileDialpadSelectedKey
	const_def
	const MOBILE_DIALPAD_KEY_1
	const MOBILE_DIALPAD_KEY_2
	const MOBILE_DIALPAD_KEY_3
	const MOBILE_DIALPAD_KEY_4
	const MOBILE_DIALPAD_KEY_5
	const MOBILE_DIALPAD_KEY_6
	const MOBILE_DIALPAD_KEY_7
	const MOBILE_DIALPAD_KEY_8
	const MOBILE_DIALPAD_KEY_9
	const MOBILE_DIALPAD_KEY_CANCEL
	const MOBILE_DIALPAD_KEY_0
	const MOBILE_DIALPAD_KEY_DELETE
	const MOBILE_DIALPAD_KEY_DONE
DEF NUM_MOBILE_DIALPAD_KEYS EQU const_value

; MobileDialpadKeys record offsets (the first two bytes are unused)
	rsset 2
DEF MOBILE_DIALPAD_VALUE      rb
DEF MOBILE_DIALPAD_X          rb
DEF MOBILE_DIALPAD_Y          rb
DEF MOBILE_DIALPAD_UP         rb
DEF MOBILE_DIALPAD_DOWN       rb
DEF MOBILE_DIALPAD_LEFT       rb
DEF MOBILE_DIALPAD_RIGHT      rb
DEF MOBILE_DIALPAD_UP_LEFT    rb
DEF MOBILE_DIALPAD_UP_RIGHT   rb
DEF MOBILE_DIALPAD_DOWN_LEFT  rb
DEF MOBILE_DIALPAD_DOWN_RIGHT rb
DEF MOBILE_DIALPAD_KEY_SIZE EQU _RS

	const_def $f0
	const MOBILE_DIALPAD_VALUE_DONE
	const MOBILE_DIALPAD_VALUE_DELETE
	const MOBILE_DIALPAD_VALUE_CANCEL

; MobileAdapterPalettes / MobileAPI_Init output
	const_def
	const MOBILE_ADAPTER_BLUE
	const MOBILE_ADAPTER_YELLOW
	const MOBILE_ADAPTER_GREEN
	const MOBILE_ADAPTER_RED
	const MOBILE_ADAPTER_PURPLE
	const MOBILE_ADAPTER_BLACK
	const MOBILE_ADAPTER_PINK
	const MOBILE_ADAPTER_GRAY
DEF NUM_MOBILE_ADAPTER_COLORS EQU const_value

; Subtract this from the SDK device ID to obtain the adapter color.
DEF MOBILE_ADAPTER_TYPE_BASE EQU $88

; sMobileTradeState / MobileTrade_RecoverSavedTrade.Jumptable
	const_def
	const MOBILE_TRADE_NONE
	const MOBILE_TRADE_OFFERED
	const MOBILE_TRADE_CHECKING
	const MOBILE_TRADE_RECEIVED
	const MOBILE_TRADE_READY
	const MOBILE_TRADE_COMPLETE
DEF NUM_MOBILE_TRADE_STATES EQU const_value

DEF TRADE_CORNER_REPLY_LENGTH EQU 105
DEF MOBILE_TRADE_EXPIRATION_DAYS EQU 11
DEF MOBILE_TRADE_MAX_CLOCK_RESETS EQU 2
