; MobileAPI calls: byte offsets into _MobileAPI.Jumptable.
	const_def 0, 2
	const MOBILEAPI_ERRORCHECK
	const MOBILEAPI_INIT
	const MOBILEAPI_WRITECONFIG
	const MOBILEAPI_ISPLOGIN
	const MOBILEAPI_DIAL
	const MOBILEAPI_HANGUP
	const MOBILEAPI_READPHONENUMBERS
	const MOBILEAPI_READUSERID
	const MOBILEAPI_READEMAIL
	const MOBILEAPI_ANSWER
	const MOBILEAPI_SMTPCONNECT
	const MOBILEAPI_SMTPSETADDRESSES
	const MOBILEAPI_SMTPSEND
	const MOBILEAPI_SMTPQUIT
	const MOBILEAPI_POP3QUIT
	const MOBILEAPI_POP3CONNECT
	const MOBILEAPI_POP3STAT
	const MOBILEAPI_POP3LIST
	const MOBILEAPI_POP3RETR
	const MOBILEAPI_POP3DELE
	const MOBILEAPI_POP3HEAD
	const MOBILEAPI_HTTPGET
	const MOBILEAPI_HTTPPOST
	const MOBILEAPI_SENDDATA
	const MOBILEAPI_SETTIMER
	const MOBILEAPI_TELEPHONESTATUS
	const MOBILEAPI_STOP
	const MOBILEAPI_END
	const MOBILEAPI_READCONFIG
	const MOBILEAPI_GETDATA
	const MOBILEAPI_TCPCUT
; A second entry pointing to the same handler as MOBILEAPI_ISPLOGIN.
	const MOBILEAPI_ISPLOGIN_ALIAS
	const MOBILEAPI_INIT_ALT
	const MOBILEAPI_TELEPHONESTATUS_ALT
DEF NUM_MOBILE_API_CALLS EQU const_value / 2

; wMobileSDK_Status bits
	const_def
	const MOBILE_SDK_BUSY_F
	const MOBILE_SDK_ERROR_F
	const MOBILE_SDK_RECV_BUFFER_FULL_F
	const MOBILE_SDK_DATA_READY_F

; MobileEZChatCategoryPointers indexes (see mobile/fixed_words.asm)
	const_def
	const EZCHAT_POKEMON
	const EZCHAT_TYPES
	const EZCHAT_GREETINGS
	const EZCHAT_PEOPLE
	const EZCHAT_BATTLE
	const EZCHAT_EXCLAMATIONS
	const EZCHAT_CONVERSATION
	const EZCHAT_FEELINGS
	const EZCHAT_CONDITIONS
	const EZCHAT_LIFE
	const EZCHAT_HOBBIES
	const EZCHAT_ACTIONS
	const EZCHAT_TIME
	const EZCHAT_FAREWELLS
	const EZCHAT_THISANDTHAT

DEF NUM_KANA EQU 45 ; length of SortedPokemon table (see mobile/fixed_words.asm)

DEF MOBILE_LOGIN_PASSWORD_LENGTH EQU 17
DEF MOBILE_PHONE_NUMBER_LENGTH EQU 20
DEF MOBILE_LOGIN_ID_LENGTH EQU 32
DEF MOBILE_URL_MAX_LENGTH EQU 165
DEF MOBILE_RECEIVE_BUFFER_SIZE EQU $1000

; wMobileDownloadFlags: bit 0 selects the second receive buffer; the high
; bits identify the API to resume when the first receive buffer fills.
DEF MOBILE_DOWNLOAD_OVERFLOW_F EQU 0
DEF MOBILE_DOWNLOAD_OVERFLOW EQU 1 << MOBILE_DOWNLOAD_OVERFLOW_F
DEF MOBILE_DOWNLOAD_POP3_RETR EQU 1 << 4
DEF MOBILE_DOWNLOAD_POP3_HEAD EQU 1 << 5
DEF MOBILE_DOWNLOAD_HTTP_POST EQU 1 << 6
DEF MOBILE_DOWNLOAD_HTTP_GET EQU 1 << 7

; Legacy three-minute limit, counted by Mobile_CheckLegacyInactivityTimeout.
DEF MOBILE_INACTIVITY_TIMEOUT_FRAMES EQU 3 * 60 * 60
DEF MOBILE_RESULT_CANCELED EQU $a
DEF MOBILE_ERROR_INVALID_DOWNLOAD EQU $d3
DEF MOBILE_ERROR_INACTIVITY_TIMEOUT EQU $d6
DEF MOBILE_ERROR_URL_TOO_LONG EQU $da

; Maximum amount of time allowed for mobile battles each day
DEF MOBILE_BATTLE_ALLOWED_SECONDS EQU 0
DEF MOBILE_BATTLE_ALLOWED_MINUTES EQU 10

; Trade corner request size
; DION addr $1e + request $8 + Name $5
; + party struct $30 + OT $5 + NICK $5
; + JP Mail struct $2a
DEF MOBILE_EMAIL_LENGTH EQU $1e
DEF TRADE_CORNER_REQUEST_LENGTH EQU $8f

DEF EASY_CHAT_MESSAGE_WORD_COUNT EQU 6
DEF EASY_CHAT_MESSAGE_LENGTH EQU EASY_CHAT_MESSAGE_WORD_COUNT * 2 ; every word uses 2 bytes

; DisplayMobileError / MobileErrorCodeTable
DEF MOBILE_SDK_ERROR_FIRST EQU $10
DEF MOBILE_SDK_ERROR_LAST EQU $33
DEF NUM_MOBILE_SDK_ERRORS EQU MOBILE_SDK_ERROR_LAST - MOBILE_SDK_ERROR_FIRST + 1
; Game-defined errors are displayed as 101-(code - MOBILE_GAME_ERROR_FIRST + 1).
DEF MOBILE_GAME_ERROR_FIRST EQU $d0
DEF MOBILE_GAME_ERROR_LAST EQU $da
DEF NUM_MOBILE_GAME_ERRORS EQU MOBILE_GAME_ERROR_LAST - MOBILE_GAME_ERROR_FIRST + 1
DEF MOBILE_ERROR_DEFAULT EQU $d9
DEF MOBILE_TEXTBOX_PALETTE EQU 6

; DisplayMobileError.Jumptable / wMobileErrorJumptableIndex
	const_def
	const MOBILE_ERROR_INIT
	const MOBILE_ERROR_WAIT_BUTTON
	const MOBILE_ERROR_INIT_NO_FADE
DEF NUM_MOBILE_ERROR_STATES EQU const_value
